(load "~/.emacs.d/customizations/flymake-ruby")

; the order of the following files is unimportant
(load "~/.emacs.d/projects/find-in-project/ido-find-in-project")
; (load "~/.emacs.d/customizations/erlang_emacs")
(load "~/.emacs.d/customizations/emacs_backup_files")
(load "~/.emacs.d/customizations/tabs")
(load "~/.emacs.d/customizations/full_screen")
(load "~/.emacs.d/customizations/tramp_customization")
(load "~/.emacs.d/customizations/keybindings")
(load "~/.emacs.d/etc/snippets/ruby-snippets-code")
(load "~/.emacs.d/etc/common_directories")
(load "~/.emacs.d/etc/spec-runner")
(load "~/.emacs.d/customizations/emacs_backup_files")
(load "~/.emacs.d/customizations/git")
